run:
  concurrency: 4
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    check-shadowing: true
    enable:
      - fieldalignment

linters:
  enable:
    - govet
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - spancheck
    - bodyclose
    - gci
    - goconst
    - gocritic
    - gosimple
    - gofmt
    - gofumpt
    - goimports
    - revive
    - gosec
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - unconvert
    - unparam
    - unused
  disable-all: false
