// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.5.3
// - protoc              v3.21.12
// source: health.proto

package health

import (
	context "context"
	codec "go.unistack.org/micro/v3/codec"
	http "net/http"
)

var (
	HealthServiceName = "HealthService"
)
var (
	HealthServiceServerEndpoints = map[string]map[string]string{
		"/live": map[string]string{
			"Method": http.MethodGet,
			"Stream": "false",
		},
		"/ready": map[string]string{
			"Method": http.MethodGet,
			"Stream": "false",
		},
		"/version": map[string]string{
			"Method": http.MethodGet,
			"Stream": "false",
		},
	}
)

type HealthServiceServer interface {
	Live(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Ready(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Version(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
