name: lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - master
    - v3
    - v4

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: checkout
      uses: actions/checkout@v3
    - name: deps
      run: go get -v -d ./...
    - name: lint
      uses: https://github.com/golangci/golangci-lint-action@v6
      with:
        version: 'latest'
