name: test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - master
    - v3
    - v4
  push:
    branches:
    - master
    - v3
    - v4

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        filter: 'blob:none'
    - name: checkout tests
      uses: actions/checkout@v4
      with:
        ref: master
        filter: 'blob:none'
        repository: unistack-org/micro-tests
        path: micro-tests
    - name: setup-go
      uses: actions/setup-go@v5
      with:
        cache-dependency-path: "**/*.sum"
        go-version: 'stable'
    - name: go work
      env:
        GOWORK=${{ github.workspace }}/go.work
      run: |
        go work init
        ls | grep -v go | xargs go work use
    - name: deps
      run: go get -v ./...
    - name: test
      env:
        INTEGRATION_TESTS: yes
      run: |
        cd micro-tests
        go test -mod readonly -v ./...
