name: syncpull

on:
  schedule:
    - cron: '* * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: init
      run: |
        git config --global user.email "vtolstov <vtolstov@users.noreply.github.com>"
        git config --global user.name "github-actions[bot]"
        git config --global url."https://vtolstov:${TOKEN}@git.unistack.org/".insteadOf "https://git.unistack.org/"

    - name: track master
      run: |
        git clone --depth=10 --branch master --single-branch ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} repo
        cd repo
        git remote add --no-tags --fetch --track master upstream-master https://github.com/${GITHUB_REPOSITORY}
        git merge --allow-unrelated-histories "upstream-master/master"
        GIT_CURL_VERBOSE=1 GIT_TRACE=1 git push --progress
        rm -rf repo

    - name: track v3
      run: |
        git clone --depth=10 --branch v3 --single-branch ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} repo
        cd repo
        git remote add --no-tags --fetch --track v3 upstream-v3 https://github.com/${GITHUB_REPOSITORY}
        git merge --allow-unrelated-histories "upstream-master/v3"
        git push --progress
        rm -rf repo

    - name: track v4
      run: |
        git clone --depth=10 --branch v4 --single-branch ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} repo
        cd repo
        git remote add --no-tags --fetch --track v4 upstream-v4 https://github.com/${GITHUB_REPOSITORY}
        git merge --allow-unrelated-histories "upstream-master/v4"
        git push --progress
        rm -rf repo
