name: prbuild
on:
  pull_request:
    branches:
    - master
    - v3
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: https://gitea.com/actions/setup-go@v3
    - name: checkout
      uses: https://gitea.com/actions/checkout@v3
    - name: deps
      run: go get -v -t -d ./...
    - name: test
      env:
        INTEGRATION_TESTS: yes
      run: go test -mod readonly -v ./...