// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.5.3
// source: handler.proto

package handler

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	codec "go.unistack.org/micro/v3/codec"
	server "go.unistack.org/micro/v3/server"
)

type meterServer struct {
	MeterServer
}

func (h *meterServer) Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error {
	return h.MeterServer.Metrics(ctx, req, rsp)
}

func RegisterMeterServer(s server.Server, sh MeterServer, opts ...server.HandlerOption) error {
	type meter interface {
	}
	type Meter struct {
		meter
	}
	h := &meterServer{sh}
	var nopts []server.HandlerOption
	nopts = append(nopts, v3.HandlerMetadata(MeterServerEndpoints))
	return s.Handle(s.NewHandler(&Meter{h}, append(nopts, opts...)...))
}
