// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.4.2
// source: handler.proto

package handler

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	codec "github.com/unistack-org/micro/v3/codec"
)

var (
	MeterName = "Meter"

	MeterEndpoints = []api.Endpoint{
		api.Endpoint{
			Name:    "Meter.Metrics",
			Path:    []string{"/metrics"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
)

func NewMeterEndpoints() []api.Endpoint {
	return MeterEndpoints
}

type MeterServer interface {
	Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
