// Code generated by protoc-gen-micro
// source: handler.proto
package handler

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	codec "github.com/unistack-org/micro/v3/codec"
)

func NewMeterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "Meter.Metrics",
			Path:    []string{"/metrics"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

type MeterServer interface {
	Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
