// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.2
// - protoc              v3.21.12
// source: handler.proto

package handler

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	codec "go.unistack.org/micro/v3/codec"
)

var (
	MeterServiceName = "MeterService"
)
var (
	MeterServiceServerEndpoints = []v3.EndpointMetadata{
		{
			Name:   "MeterService.Metrics",
			Path:   "/metrics",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
	}
)

type MeterServiceServer interface {
	Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
