name: test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - master
    - v3
    - v4
  push:
    branches:
    - master
    - v3
    - v4

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        filter: 'blob:none'
    - name: setup go
      uses: actions/setup-go@v5
      with:
        cache-dependency-path: "**/*.sum"
        go-version: 'stable'
    - name: setup deps
      run: go get -v ./...
    - name: run test
      env:
        INTEGRATION_TESTS: yes
      run: go test -mod readonly -v ./...
